### ISSUE TITLE
Create a messaging table

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#130]
As an admin, I want to be able to send messages to people in a contest

potential db structure 

id | contest id | type | subject | body
| --- | --- | --- | --- | ---|
auto int | int | enum | varchar | long text 
1 | 5 | reminder | something | something

**Comment by weerd** [comment]
`enum` are @angaither favorites

**Comment by weerd** [comment]
@angaither A bit concerned on making `type` an `enum`... was [reading](http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/) up on this and doesn't seem like it's the best idea to use it unless we're absolutely sure of the finite set of options. It made sense in [**Longshot**](https://github.com/DoSomething/longshot/blob/c4ae29de785a879abc9feb9dfdbf6a0cab25593d/app/database/migrations/2014_10_06_115722_create_ratings_table.php#L18) where the options were, `yes, no, maybe`, but for email types we could end up adding/removing them.

Up for discussing further, just want to make sure it's not something that'll be a pain to amend later...

**Comment by weerd** [comment]
The `type` column could just be a `varchar` (kinda like we're doing w/ roles right now) and not have a dedicated table of message types. It would allow room for adding more or removing any since it's just a simple string in the DB and can be anything in that column.
