### ISSUE TITLE
Allow admins to customize and create message content

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#137]
As an admin I would like to set up the text for messaging when I create a contest. 

__feelings__ 
- setting these should be optional, not required  :open_file_folder: 
- i would imagine this should also be ~smashable~ :octopus: 
- this should also handle basic text replacement of :repeat: 
  - first name :name_badge: 
  - end date :calendar:

**Comment by weerd** [comment]
@angaither So not sure about the "smashable" since we're using Forge. The smashable was a JS component of Bootstrap. We could maybe add a new component for Forge though...

**Comment by sbsmith86** [comment]
@weerd i think we should add it for forge-admin :hammer:

**Comment by weerd** [comment]
Gah! Closing my issue @sbsmith86 :confounded: But yeah, good idea for making it a component for Forge-admin :dancer:
