### ISSUE TITLE
Add send from value

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#143]
As an admin I want to set who is sending the email, per contest. 

this includes: 
Name & email address

**Comment by weerd** [comment]
@angaither So should this be a field on the `contests` table then? Otherwise it would be a field on each separate message per contest, which could be fine too? I'm assuming 1 admin per contest so probably want it attached to the contest model.

**Comment by angaither** [comment]
@weerd yeah, per `contest`

**Comment by weerd** [comment]
cool :sunglasses:
