### ISSUE TITLE
Create a leaderboard day variable

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#145]
As an admin, when splitting a `contest` I want to specify which **day** a user will get `leaderboard` email updates, this is per `competition` 

Notes: 
- This isn't to automatically send the emails, it's to add it in as a variable in the content)
- This should be an actual day of the week. (sunday, monday, wednesday)
- Another variable we want in the `reminder` email is the day of the week, minus one
 - for example, leaderboards are sent on `Monday` and we want a reminder email to say, upload your rb by `Sunday`
 - I'm not even sure if we can do math on days of the week :elephant: :calendar:

**Comment by mikefantini** [comment]
If we can't do math on days of the week then we'd want to ask for Leaderboard Day Eve when splitting a `contest`. 

Leaderboard Day Eve - A magical day of high anticipation for children throughout the land.

**Comment by deadlybutter** [comment]
I feel like theres a way with Carbon

**Comment by sbsmith86** [comment]
think you can do `$date->subDay(); ` according to the docs
