### ISSUE TITLE
Create top 3 reportbacks "variable"

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#147]
As an admin, I want to automatically pull the top 3 (by quantity) reportback images into the email

- pull in the most recent reportback photo
 - it must have already been approved
- include the `first name` `quantity` `photo caption`

**Comment by sbsmith86** [comment]
This looks like a dupe of #195 which I created and assigned to myself. I was gonna hop on pulling in top three reportbacks while the leaderboard optimization work was being done.

@mikefantini @deadlybutter ok if I just move forward with this one?

**Comment by mikefantini** [comment]
@sbsmith86 go for it!

**Comment by sbsmith86** [comment]
Closing out. work on this is being done in #195
