### ISSUE TITLE
Create variable/token standards

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#153]
We need a way to grab & replace the variables we are using

- standard way of naming things
  -  `[Model:attribute]` so an example `[Contest:end_date]` or just `:column_name`
  - also need to think about what we will call the things from phoenix
- an easy way to replace the content 

Tokens
---------
#### Gladiator
- `:sender_name`
- `:sender_email` : maybe not a token, but needed for the `from` var
- `:leaderboard_msg_day`
- `:leaderboard_msg_day-1`
- `:end_date` (competition end date) 
- `:pro_tip`

#### User cache 
- `:first_name` 

#### Phoenix cache
- `:campaign_title` 
- `:reportback_noun` 
- `:reportback_verb`
- `:link_to_campaign#prove` (this should be a better name but I wanted to ~describe~ it)

#### Calculated tokens
- `:top_three_reportbacks` (by quantity)
  - includes [`:first_name`, `:caption`, `.reportback_noun`, `:reportback_quantity`, `:reportback_photo`]
- `:leaderboard`

**Comment by angaither** [comment]
we could also do [this](https://laravel.com/docs/4.2/templates#extending-blade)

**Comment by angaither** [comment]
thinking about accessors as well, but I don't think we will have the variables we need to pass them in correctly
also when displaying the content, it'll appear to be replaced already. hmm

**Comment by sbsmith86** [comment]
Don't know if this is helpful, but could we define an array of tokens/variables and then create a function that does the replacement? like this...

```
$replace = [':drink' => 'coffee', ':name' => 'Ricardo'];
$str = 'Hi my name is :name. I like to drink :drink.';

echo str_replace_dynamic($replace, $str);

function str_replace_dynamic(array $replace, $string) { 
   return str_replace(array_keys($replace), array_values($replace), $string);    
}
```

Found it here: http://laravel.io/forum/07-16-2014-how-do-i-replace-the-words-of-a-text

**Comment by angaither** [comment]
@sbsmith86 yeah, that's a similar approach to what we did in the [scholarship app](https://github.com/DoSomething/longshot/blob/c4ae29de785a879abc9feb9dfdbf6a0cab25593d/app/models/Email.php#L15)

**Comment by DFurnes** [comment]
Yeah, I like the solution @sbsmith86 posted. :+1: You could maybe use a `$tokenizable` property on each model class with the fields you want to be able to be accessed from tokens like this (or just allow anything and exclude `$hidden`)?

**Comment by sbsmith86** [comment]
ooo that's a cool idea @DFurnes

**Comment by angaither** [comment]
do [this](https://github.com/DoSomething/gladiator/pull/164#discussion_r58219832)

**Comment by sbsmith86** [comment]
hmm should `:pro_tip` be a token? It's already a field in the message so like we just have to print it out in the email template if the field isn't empty.

**Comment by angaither** [comment]
@sbsmith86 right, but you have to figure out where inside the body to print it?

**Comment by sbsmith86** [comment]
@angaither oh i guess i just figured it would be in a standard spot in the template, but this works to.

**Comment by angaither** [comment]
@sbsmith86 hm, well it might be. if you would rather have it directly in the message, that works for me. just wanted to account for it above

**Comment by deadlybutter** [comment]
should `:leaderboard_msg_day-1` be `:leaderboard_msg_day+1` ? (I mean thats what its actually doing)

**Comment by angaither** [comment]
@deadlybutter I don't think so?
the leaderboard message goes out on wednesday, you want to remind people to submit updates one day before that so on tuesday

**Comment by deadlybutter** [comment]
@angaither @sbsmith86 Based on this doc I think we also need a :rules_link  (Or is this auto appended to each message like a terms of service?)

https://docs.google.com/document/d/1AX0tVVzgVhtyXVBn-56OFaz7k59rpxQedGKp4dFx6YY/edit

**Comment by deadlybutter** [comment]
also just to confirm, :link_to_campaign works without #prove right? cause we need both

**Comment by angaither** [comment]
@deadlybutter where are you seeing the `:link_to_campaign` without prove?

**Comment by mikefantini** [comment]
@sbsmith86 any tokens that you aren't able to finalize for this sprint can you please create a new issue for any that are remaining for next sprint (i.e. leaderboard and top 3 info)

**Comment by sbsmith86** [comment]
@mikefantini will do.

**Comment by sbsmith86** [comment]
As of this issue this is the current list of tokens available. Going to close this and create a new issue for the remaining tokens that we need to implement. 
```
:end_date:
:leaderboard_msg_day:
:leaderboard_msg_day-1: 
:first_name:           
:sender_name:          
:campaign_title:        
:reportback_noun:     
:reportback_verb:
:prove_it_link:
```

NOTE: Links can be created by doing `[text or token](link or token)`
