### ISSUE TITLE
Email performance issues

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#175]
Sending email to a bunch of users works, but I did receive a 504 gateway timeout when doing it on QA to 260 users.

Possible solution is to do the message processing (finding and replacing tokens) in the event that gets sent to the queue. Right now it is happening before we fire the event so which is probably slowing things down.

**Comment by sbsmith86** [comment]
In #186 I moved the "message processing" stuff that handles all the token replacement into the event handler that gets queued. I think this should take care some of the issues we were seeing with timeouts since that is probably the heaviest work in this process and now it will run in the background.

**Comment by deadlybutter** [comment]
After the update commented on above, it's not exactly clear where the bottle neck is?

**Comment by sbsmith86** [comment]
@joe i haven't really dug into it yet. might need to queue message processing separately or something.  it definitely still sends all the messages to mandrill, but don't understand why it causes the page to timeout as i thought queue jobs run in the background.

**Comment by deadlybutter** [comment]
![screen shot 2016-04-21 at 10 34 50 am](https://cloud.githubusercontent.com/assets/897368/14712826/b63b6878-07ac-11e6-8ffa-2e00543e201a.png)
