### ISSUE TITLE
Pull more reportback info into gladiator

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#183]
potentially helpful things
- reportback item `caption`
- `why_participated`

**Comment by weerd** [comment]
This is all now pulled into Gladiator. All the Reportback info we normally get from our Phoenix API is now (on the fly) attached to the user object. There's a couple ways to do it in the codebase based on where the call is coming from, but usually just a matter of calling a specific method `appendReportback()` or when getting a collection of users for a model, passing `true` as the second parameter to `getModelUsers($model, true)`.

**Comment by weerd** [comment]
However, the above items do need to get added to the CSV export, which is the next task!

**Comment by angaither** [comment]
@weerd I think also in the leaderboard, but perhaps Hilary/Chris will have opinions on that

**Comment by weerd** [comment]
Yeah, these items can easily be added there as well, but maybe would recommend a dedicated view, because the table is getting kinda large and will be unreadable w/ long messages in a `caption` and `why participated` columns 😬
