### ISSUE TITLE
Add more info to competitions

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#189]
It would be great to have the following information calculated per competition:

- [x] # of ppl who reported back
- [x] reportback rate: # of ppl who reported back/# of ppl in competition (or contest)
- [x] non-flagged impact quantity

**Comment by mikefantini** [comment]
# of ppl who reported back and non-flagged impact quantity are things that could ideally be used as tokens in emails as well.

**Comment by angaither** [comment]
this is maybe impossible.

**Comment by weerd** [comment]
@angaither @mikefantini did you still want me to add an issue for info on the Contest level?

**Comment by mikefantini** [comment]
@weerd yeah I think breaking this out into two issues one for contests one for competition would be great. Thanks!
