### ISSUE TITLE
Test email functionality

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#198]
We need to build out a better way for admins to test emails before sending.

Current behavior: On QA, admin clicks send and one email will be sent to the person who is designated the sender email on the contest. In prod, if and admin clicks send, it will really send this email to every person in the competition

Desired behavior: We provide a test email button that just fires off and email to the admin this way emails can be tested in QA and prod.

**Comment by mikefantini** [comment]
Marked as high priority as this is blocking sending any emails out since we want to test them first before sending to actual users.
