### ISSUE TITLE
User Reportback Item status for leaderboard information

### ISSUE THREAD

**Issue by weerd** [DoSomething/gladiator#205]
We are currently using the `/signups` endpoint to retrieve Reportbacks and Reportback items for user contestants.

The status in the leaderboard of a submission is currently based on the `flagged` status of a Reportback. However, if we want to display status of a submission, such as which ones are `promoted`, `approved`, `flagged` (different from Reportback flagging), etc, we need to be referencing the `status` property on the individual Reportback Items for a particular "parent" Reportback.

_*Side Note:_ Eventually, we may want to switch to using the `/reportbacks` endpoint and allow passing a `users` parameter to the API (update to Phoenix API needed), instead of going through the `/signups` endpoint, since we _already_ know that all these users are signed up because they are specifically _in_ a competition. So we're requesting a bunch of extraneous data and complicating the logic by having to go through the `/signups` endpoint.

**Comment by mikefantini** [comment]
Just to be clear what admins really need to know is 1. whether any files have been flagged and 2. whether any files have yet to be reviewed.

So if one column is "flagged_status" and another is "number of files pending" this would probably get us what we need.

**Comment by mikefantini** [comment]
And we'd need this in the leaderboard and export.

**Comment by mikefantini** [comment]
@weerd mind taking on this one tomorrow?

**Comment by weerd** [comment]
@mikefantini by "competition export" do you mean the initial export that is done right when a competition is about to launch?
