### ISSUE TITLE
Hyperlinks not working in gladiator emails

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#213]
Both times "Prove It' shows up in the email below the phrase should be linked to the #prove URL of the campaign (i.e. https://staging.dosomething.org/us/campaigns/patient-playbooks#prove)

![image](https://cloud.githubusercontent.com/assets/6330971/14532283/8f65304a-022e-11e6-9c41-ade4b1507376.png)

**Comment by sbsmith86** [comment]
I added support for markdown-like link syntax, so you should be able to do:

`[Prove It](:prove_it_link:)`

I think the issue here is that the default messages weren't updated with that! So I will handle that for sure! good catch.

**Comment by DFurnes** [comment]
> I added support for markdown-like link syntax, so you should be able to do:
>
> `[Prove It](:prove_it_link:)`

:heart_eyes:

**Comment by mikefantini** [comment]
This will be taken care of with #215.
