### ISSUE TITLE
Default email updates

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#215]
**Welcome email body updates:**

Woohoo, so glad you signed up for my :campaign_title: competition, :first_name:! Feel free to get a head start on the competition! Again, winners will be selecting based on the greatest number of :reportback_noun: :reportback_verb:. 

I’ll be in touch with more info in the next few days. Excited to watch you climb the leaderboard and crush the competition! 

:sender_name:

-------

**Competition info email body updates:**

Just wanted to send along some more info about the :campaign_title: competition you signed up for! The rules are simple:

1. The more :reportback_noun: :reportback_verb:, the higher you move up the leaderboard.

2. To be considered, go to the [Prove It](:prove_it_link:) section of the campaign and upload a photo a clearly shows you and all :reportback_noun: :reportback_verb:. Submissions are due each :leaderboard_msg_day-1: night throughout the campaign.

The competitor with the most :reportback_noun: :reportback_verb: by the competition deadline of :end_date:, wins $100 on an Amex gift card. 2nd - $50, 3rd - $25.

Your first update is due on :leaderboard_msg_day-1: before 10 PM EST. If you have an update for me and want to see yourself on :leaderboard_msg_day:’s leaderboard, simply:

   - Go to the [Prove It](:prove_it_link:) section

   - Upload your photo

   - Click “submit your pic”

On :leaderboard_msg_day:, I will send you the updated standings so you can see yourself on the leaderboard.

Rootin’ for ya, :first_name:,

:sender_name:

--------

**Where are you? Check status email body updates:**

I noticed you haven’t upload a picture of your :reportback_noun: :reportback_verb: to :campaign_title: yet. Just wanted to see if everything is ok! 

If you are able, you still have until :leaderboard_msg_day-1: to be included in the next update! Take a picture and upload your photo [here](:prove_it_link:). 

Let me know if I can help you, :first_name:. 

:sender_name:

-----------

**Reminder for first submission due email body updates::**

Hey, :first_name:! 

Just a reminder that your next update is due :leaderboard_msg_day-1: before 10:00 PM EST. If you want to see yourself on the leaderboard, [upload a photo](:prove_it_link:) showing you and all :reportback_noun: :reportback_verb:. 

On :leaderboard_msg_day:, I will send you the updated standings. 

Let me know if I can help, :first_name:! 

:sender_name:

---------------

**Reminder for submission photo due email body updates:**

:first_name: ­

Your next update is due tonight before 10pm est, so if you want to make the leaderboard and see your name featured, [upload your photo](:prove_it_link:) with all your :reportback_noun: :reportback_verb:. 

Can’t wait to see it! 

:sender_name:

---------------

**Almost over reminder email subject updates:** (note this is for the subject, not the body)

This :campaign_title: competition is almost over, :first_name:!

---------------

**Almost over reminder email body updates:**

Last call: The final deadline for this competition is this :leaderboard_msg_day-1: night before 10:00 PM EST! 

When you’re ready, [upload your final photo](:prove_it_link:) showing all your :reportback_noun: :reportback_verb:. If you’re updating your submission with a new photo, simply click “add another photo” and write in how many :reportback_noun: you :reportback_verb:. 

Looking forward to seeing your final pic, :first_name:! 

 :sender_name:

-----------------

**Last minute reminder email body updates:**

:first_name:, 

The :campaign_title: Competition closes at 10:00 PM EST TONIGHT. Take this moment to [upload your final photo](:prove_it_link:) clearly showing you and all :reportback_noun: :reportback_verb:. 

I will send the final results tomorrow, so keep your fingers crossed. Thanks for doing an awesome job to make an impact! 

:sender_name:

----------------

**Leaderboard update email body updates:**

Hello Competitors, 

Here is your first official :campaign_title: competition update! The competition ends on :end_date:. Finish in the top 3 in :reportback_noun: :reportback_verb: and win: 

- 1st place: ­ $100 amex card
- 2nd place: ­ $50 amex card 
- 3rd place: ­ $25 amex card 

Two more weeks to increase your number of :reportback_noun: :reportback_verb: to move up the leaderboard! [Upload your photos here](:prove_it_link:).

Pro tip ­- :pro_tip: 

Next :reportback_noun: will be due :leaderboard_msg_day-1: before 10pm est. 

Here is the leaderboard! Shoutouts to the top 3 below: 

-------------

**Leaderboard update 2 email body updates:**

Hello, competitors-- 

1 more week! This :campaign_title: competition ends on :end_date:, so it’s time to make your mark. 

Pro tip - :pro_tip: 

A final photo with your :reportback_noun: will be due :leaderboard_msg_day-1: before 10pm EST. [Upload yours here](:prove_it_link:).

Here is the leaderboard! Shoutouts to the top 3 below:

[#] more weeks to make your mark and climb up the leaderboard!

----------------

**Final leaderboard update email subject updates:** (not subject not body)

Here are the :campaign_title: competition winners!

----------------

**Final leaderboard update email body updates:**

This is it, the final leaderboard and results. Thank you for spending these last 3 weeks, working hard not only to climb the leaderboard, but also to affect lives around you and make the world a better place. 

Here is your final leaderboard. Pics, prizes and honorable mentions below:

**Comment by mikefantini** [comment]
Seems like github is messing with some of the markdown (which makes sense) but if you view the edit of the issue you should be able to copy and paste what the exact messages need to be including links to prove it section.

**Comment by mikefantini** [comment]
Getting this done should let us close out #213 correct @sbsmith86?

**Comment by sbsmith86** [comment]
Yep!
