### ISSUE TITLE
Error when trying to send final leaderboard update email

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#220]
Got this error intermittently when trying to send the final leaderboard update email:

![image](https://cloud.githubusercontent.com/assets/6330971/14541646/ef44ba06-0258-11e6-984e-0a9dfbbbd4f2.png)

Let's just keep our eyes out for it.

**Comment by deadlybutter** [comment]
I just sent a test one off, is this a consistent bug or just "random"?

**Comment by mikefantini** [comment]
@deadlybutter I was getting the error intermittently.
