### ISSUE TITLE
Testing welcome email

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#241]
As an admin, I'd like to be able to send myself a test email of the welcome email users receive in #240.

Ideally the user could send this email from the /contests/[cid] view. Perhaps we can add a button to the messaging section of this view to send a test welcome email. Functionally this should work the same way as test emails do for individual competitions (i.e. a user gets sent to the sender email address).

**Comment by deadlybutter** [comment]
after adding this, lets kill it from the messages page as @sbsmith86 mentioned here https://github.com/DoSomething/gladiator/pull/251#issuecomment-214479290
