### ISSUE TITLE
Migrations failing

### ISSUE THREAD

**Issue by weerd** [DoSomething/gladiator#257]
![image](https://cloud.githubusercontent.com/assets/105849/14861963/76f674e8-0c7d-11e6-89a7-28abece0e760.png)

@deadlybutter added a new migration but he mentioned he was getting an error with the prior migration for adding the `shoutout` field as well.

**Comment by deadlybutter** [comment]
yeah, same error just different migration name when i was trying to migrate before. to get around i just deleted the entire DB and migrated.

**Comment by sbsmith86** [comment]
did you try `composer dump-autoload`?

**Comment by weerd** [comment]
nope! that was it :facepalm:
