### ISSUE TITLE
Create endpoint for phoenix to get waiting rooms

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#26]
phoenix needs to ping this app to determine if there should be a competition on the node.

**Comment by sbsmith86** [comment]
@angaither isn't this what the flag on the sign up data form is for?

**Comment by angaither** [comment]
@sbsmith86 yeah, was thinking we could automatically set that instead of configuring the competition in two places (that leaves a lot of room for error) 
DoSomething/phoenix/issues/6225

**Comment by weerd** [comment]
automate all the things!

**Comment by sbsmith86** [comment]
Oh! cool.

**Comment by deadlybutter** [comment]
@weerd is it convention to use the existing waiting room controller here, or do we separate out API controllers/routes?

**Comment by weerd** [comment]
I've got an upcoming PR that will deal with that. Pushing up User CRUD first and then API shiz separate. Chatted with @DFurnes and seems like it's better to separate it out.

**Comment by deadlybutter** [comment]
okie dokes, thanks @weerd
