### ISSUE TITLE
Unable to send emails from QA

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#266]
I keep getting blocked on testing messaging because emails aren't sending via QA.

I doubt this has anything to do with it but should we try taking QA out of test mode and see if I can just test by sending test emails vs. actually sending emails to all competitors?

**Comment by angaither** [comment]
we should be good on this now, I updated kept the `log` file with #296 and @sheyd started the Supervisor thing so it will autorestart after deploy & if it quits
