### ISSUE TITLE
Welcome email not pulling in first name token properly

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#270]
![image](https://cloud.githubusercontent.com/assets/6330971/14892510/13b32824-0d39-11e6-8b1c-544f178ea1bf.png)

![image](https://cloud.githubusercontent.com/assets/6330971/14892505/0c3073f4-0d39-11e6-83b7-83b1f26ee7d2.png)

All other tokens seem to be working properly for that email.

This token also appears to be working for other emails.

**Comment by deadlybutter** [comment]
fixed 
![screen shot 2016-04-28 at 1 08 42 pm](https://cloud.githubusercontent.com/assets/897368/14894603/60e9ba00-0d42-11e6-8187-f0059afcefbb.png)
