### ISSUE TITLE
Competition info email not sending

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#272]
Steps to replicate:

- Go to https://qa-gladiator.dosomething.org/competitions/13/messages/33
- Try to send "Competition Info" email
- Verify in mandrill that no emails were sent

**Comment by sbsmith86** [comment]
i'll take a look.

**Comment by sbsmith86** [comment]
ahh i know why this is happening. the info email template is pulling in a `$body` variable but after the leaderboard updates, the `body` field is passed in an array with all the content so we need to do `{{ content['body'] }}` thought I had updated all instances of this, but seems I missed this one. I have a [branch]( #277 ) open that should fix this once I finish it.
