### ISSUE TITLE
Leaderboard Enhancements

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#275]
- [x] remove "Top Three Reportbacks"
- [x] update copy of top 3 for leaderboard update 1 and 2 (see below)
- [x] update copy of top 3 for final leaderboard update (see below)
- [x] update column of leaderboard from quantity to "Number of :reportback_noun: :reportback_verb:"
- [x] put user captions in quotes and make them italicized
- [x] keep the size of all text the same as the body text, but let's keep user names bold and "Leaderboard" header bold

**Leaderboard update 1 and 2 top 3**
- Top spot - Our current leader with :rb_quantity: :reportback_noun:...
- 2nd - In 2nd place with :rb_quantity: :reportback_noun:...
- 3rd - In 3rd place with :rb_quantity: :reportback_noun:...

![image](https://cloud.githubusercontent.com/assets/6330971/14922149/e82e3fe2-0e03-11e6-9df9-72ef1f865cd3.png)

**Final leaderboard update top 3**
Top spot -

Our winner, with :rb_quantity: :reportback_noun:...
Taking home the $100 AMEX gift card...

2nd - 

In 2nd place with :rb_quantity: :reportback_noun:...
Winner of the $50 amex gift card...

3rd - 

In 3rd place with :rb_quantity: :reportback_noun:...
Winner of the $25 amex gift card...

**Comment by mikefantini** [comment]
note for cleanup: captions in italics and quotes

**Comment by mikefantini** [comment]
@sbsmith86 I think this should be fully updated. Also I chatted with Chris and we're going to keep the order 1, 2, 3. Let me know if you have any questions.

**Comment by sbsmith86** [comment]
@mikefantini question about the text for the final leaderboard update, this text:

> Taking home the $100 AMEX gift card...

won't be the same for every competition and we don't have fields for prizes. Do we 1) need fields so that that we can pull in prize info to the emails, or 2) can we remove it?

**Comment by sbsmith86** [comment]
Or is the prize always the same?

**Comment by mikefantini** [comment]
@sbsmith86 the plan is for the prize to always be the same.

**Comment by sbsmith86** [comment]
@mikefantini ahh kay! cool
