### ISSUE TITLE
Add summary statistics of Competitions to Contest

### ISSUE THREAD

**Issue by weerd** [DoSomething/gladiator#281]
This references a task similar to that of #189, but at the Contest level, to add a bunch of useful statistics that collects data for all Competitions in a Contest.

This will be a bit harder to accomplish, however there are a few approaches we could try. The issue is that it's very data intensive to grab all User activity for each user across all competitions with reportbacks, etc and traversing the external APIs to collect it all.

One approach suggested by @angaither would be to determine an appropriate Phoenix API call that could handle grabbing all the data needed in one call to Phoenix and return the data back to then parse the stats.

Another approach could be to utilize a queue worker to handle periodically (once a day) collecting all the necessary info using some of the existing methods in Gladiator, but for all the competitions in a contest, and then cache them with a reasonable expiration that would not be taxing on the system.

But something to consider for vNotRightNow.

cc: @mikefantini

**Comment by sbsmith86** [comment]
Admins are using lookr for stats. Closing this for now.
