### ISSUE TITLE
Welcome email not sending in production

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#282]
#240 is not actually sending in production

It was sending in QA previously but no longer seeing it send from QA

**Comment by deadlybutter** [comment]
works fine on my computer

![screen shot 2016-04-29 at 1 23 12 pm](https://cloud.githubusercontent.com/assets/897368/14923843/9a22478a-0e0d-11e6-805a-ea38a64ed792.png)

**Comment by mikefantini** [comment]
@deadlybutter is this on prod or on your local?

**Comment by deadlybutter** [comment]
local

**Comment by deadlybutter** [comment]
works on staging, sorta

![screen shot 2016-04-29 at 2 03 14 pm](https://cloud.githubusercontent.com/assets/897368/14925000/27ac5370-0e13-11e6-8274-b2dcee14f7a6.png)

:first_name: wasnt replaced for some reason

**Comment by deadlybutter** [comment]
oh its :first_name without the ending quote, everything is fine

**Comment by deadlybutter** [comment]
im not sure if the current problem we're talking about in #competitions is related, but it might be.

I cant think of any code specific reason its broken, as it works everywhere else ^

**Comment by mikefantini** [comment]
@deadlybutter I just signed up for competition in prod and received this email so it seems to be working now... any idea why?

**Comment by deadlybutter** [comment]
@mikefantini literally nothing makes sense anymore fantini, thats where my head is right now
