### ISSUE TITLE
contests export help text is wrong

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#299]
I just exported the list of users in a contest from ~comeback clothes~
![image](https://cloud.githubusercontent.com/assets/645205/15022000/92e18f56-11f7-11e6-99ee-bb8f81447b5a.png)
and got this
![image](https://cloud.githubusercontent.com/assets/645205/15021993/8755c40e-11f7-11e6-996f-fec3409598c6.png)

**Comment by weerd** [comment]
This got fixed in #300. Just forgot to reference it!
