### ISSUE TITLE
Limit attempts on failed jobs in redis queue

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#301]
We currently have jobs in the queue that have run over 500,000+ times. Apparently there is an option to limit the amount of tries that we allow, we should probably update this to some reasonable number. 

[See the documentation](https://laravel.com/docs/5.1/queues#writing-job-classes) (scroll down to "when things go wrong")
> If an exception is thrown while the job is being processed, it will automatically be released back onto the queue so it may be attempted again. The job will continue to be released until it has been attempted the maximum number of times allowed by your application. The number of maximum attempts is defined by the `--tries` switch used on the `queue:listen` or `queue:work` Artisan jobs.

**Comment by sbsmith86** [comment]
Update looks like we need to do this: https://laravel.com/docs/5.1/queues#dealing-with-failed-jobs to deal with the failed jobs table but we also need to set that `--tries` flag to set the number allowed

**Comment by sbsmith86** [comment]
@blisteringherb Do I have to just add the `--tries` flag on this line? 

`run "ps -ef | grep 'queue:work' | awk '{print $2}' | xargs sudo kill -9"`
https://github.com/DoSomething/gladiator/blob/master/config/deploy.rb#L48

if so, where exactly does it need to be added in that line? like this?
`run "ps -ef | grep 'queue:work --tries=10' | awk '{print $2}' | xargs sudo kill -9"`

If you show me that, I think I can take this issue and deal with the app level stuff.

**Comment by blisteringherb** [comment]
I’ve added the `—tries=3` flag to this command `php /var/www/gladiator/current/artisan queue:work --daemon --sleep=5 --tries=3` which supervisor restarts if it crashes. I’m hoping that fixes the issue. that flag was set on footlocker though so it should work.
