### ISSUE TITLE
default messaging is empty

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#309]
![image](https://cloud.githubusercontent.com/assets/645205/15081878/f5e4660e-1392-11e6-8709-6e2becb24d30.png)

**Comment by angaither** [comment]
also hitting submit causes this 
![image](https://cloud.githubusercontent.com/assets/645205/15081920/21dade0a-1393-11e6-97f3-e6bd5b99d923.png)

**Comment by mikefantini** [comment]
Also don't show up when creating a new contest:

![image](https://cloud.githubusercontent.com/assets/6330971/15082412/8e8d8fb4-1395-11e6-8b31-a082eab4e73b.png)

**Comment by weerd** [comment]
Turns out it's just that we need to run `php artisan db:seed --class=MessageSettingTableSeeder` to seed the `messages_settings` table in the database on both QA and Prod.

**Comment by weerd** [comment]
All set. Messages Settings are now available on both QA & Prod!
