### ISSUE TITLE
Zero-index message keys

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#321]
There is [logic](https://github.com/DoSomething/gladiator/blob/master/resources/views/messages/partials/_reportback.blade.php) that depends on the different leaderboard messages being zero-indexed, but the settings messages and the default messages defined in the `Correspondence` class are one-indexed (? is that a thing? shrug ) so we need them to be zero-index so it is more inline with 💻  and the logic will work.

**Comment by angaither** [comment]
seems like this is still happening

**Comment by sbsmith86** [comment]
I think I identified one issue here...we deployed the new code, which fixes the correspondence class but on prod we didn't re-seed the DB so the default messages were still indexed wrong, and therefore, all new contests get messages with the wrong ids...I just updated this in prod: 

before: 
<img width="374" alt="screen shot 2016-06-28 at 3 47 37 pm" src="https://cloud.githubusercontent.com/assets/1700409/16430144/285aeff2-3d48-11e6-948e-ec88e67a44cc.png">

after

![image](https://cloud.githubusercontent.com/assets/1700409/16430148/2ca3e4d8-3d48-11e6-89fb-7c50edc2c0ab.png)

**Comment by sbsmith86** [comment]
This should be fixed. I just created a fake contest on prod and double checked all the message keys in the DB and things look good. 

Looks like we were still seeing issues because contest 12 and 13 in prod did not have all of their message keys updated to be zero-index. I just manually went in and fixed this. Will continue to monitor but i think this is ok to close now.
