### ISSUE TITLE
Toggle leaderboard images on/off

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#331]
Allow admins to turn displaying images in the leaderboard email on/off easily.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;WnQyw3sp&#x2F;1589-gladiator-feature-to-edit-the-leaderboard-photos"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Gladiator -- Feature to Edit the Leaderboard Photos</a>
