### ISSUE TITLE
Slow load time with competition ID

### ISSUE THREAD

**Issue by ngjo** [DoSomething/gladiator#339]
#### Current Behavior

When you click on a competition ID, it can take upwards of 30+ seconds to load or just crashes.
#### Desired Behavior

Competition ID loads quickly w/o issues
#### Steps to Replicate
1. Go to gladiator
2. Click on a contest (the number)
3. Scroll and click on a competition ID
4. Depending on your luck, it may or may not load immediately, crash, or take some time to load
#### Why This Matters

This is inefficient and mucks up a smooth workflow.
#### Relevant Screenshots + Links

Competition IDs within a Contest: https://gladiator.dosomething.org/contests/18

![screen shot 2016-09-09 at 12 17 01 pm](https://cloud.githubusercontent.com/assets/2658867/18394317/5298e35a-7687-11e6-8f6d-dc84cde009c8.png)

Note: I've seen slow load times when clicking on the Leaderboard button in a competition too -- not sure if it's the same thing causing this.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;R62uySs9&#x2F;28-as-a-developer-i-want-to-increase-the-load-time-when-someone-clicks-on-a-competition-id-so-that-it-doesn-t-take-so-long-or-time-"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a developer, I want to increase the load time when someone clicks on a competition ID so that it doesn&#39;t take so long (or time out)</a>

**Comment by sbsmith86** [comment]
Gonna close this for now as it seems to be better. But lets keep an eye on it.
