### ISSUE TITLE
Showing contest level stats (summary of competition level stats)

### ISSUE THREAD

**Issue by ngjo** [DoSomething/gladiator#343]
#### User Story

As an admin, I have to report stats at both the contest and competition level. Right now, Gladiator shows stats at the competition level, but not the contest level:

https://gladiator.dosomething.org/competitions/83
![screen shot 2016-09-12 at 1 53 45 pm](https://cloud.githubusercontent.com/assets/2658867/18446564/e277bf26-78f0-11e6-8ea2-f368614774c6.png)

The Super Stress Face Contest (https://gladiator.dosomething.org/contests/17) has 3 separate competitions:

![screen shot 2016-09-12 at 1 59 03 pm](https://cloud.githubusercontent.com/assets/2658867/18446605/1cb839fe-78f1-11e6-8cad-0c8ef2b67102.png)

I would like to see the same Statistics to show up at the contest level and be the combination of the separate contests. Here are the statistics:
- Total number of contestants in competition:
- Number of contestants who have reported back:
- Reportback rate: 
- Approved reportbacks impact quantity: 
#### Why This Matters

Impact team reports these stats to campaign team and allows them to make appropriate tweaks to the competition wording. 
#### Current Workaround w/o Feature (if applicable)

Impact team manually copies and tracks the individual competition stats in a google doc and sums it up for the contest.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bBfX8eaZ&#x2F;32-as-an-impact-team-member-i-want-to-see-contest-level-stats-so-that-i-can-quickly-see-how-an-entire-contest-is-doing-instead-of-p"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As an impact team member, I want to see contest level stats so that I can quickly see how an entire contest is doing instead of pulling individual competition data.</a>

**Comment by sbsmith86** [comment]
Admins are using looker for this so going to close for now.
