### ISSUE TITLE
waiting room CRUD

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#4]
create a new waiting room for a cohort of people who said yes to a competition and were forward from phoenix

This should have node id, run id, and signup dates

DoSomething/phoenix/issues/6170

**Comment by deadlybutter** [comment]
@sbsmith86 how far along are you with this? im workin on #6 and dont wanna interfere with anything youre working on here

**Comment by sbsmith86** [comment]
@deadlybutter was having some issues setting up gladiator, but im like ehhhh half way-ish done with this. Shouldn't be too long. Not sure #6 will conflict with it though. Is the split method going in the controller?

**Comment by deadlybutter** [comment]
I was planning on putting it in the controller/show view -- do you think it should be somewhere else?

**Comment by weerd** [comment]
yeah, the controller should only be concerned with gathering info and showing it places. I was thinking it could be a method on the `WaitingRoom` model? also, we should probs discuss this in the corresponding issue ;)

**Comment by deadlybutter** [comment]
discussion in the right place? thats a terrible idea @weerd .... _walks over to the right issue_
