### ISSUE TITLE
Leaderboard messages not sending

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#407]
Leaderboard messages for the [Sincerly, Us](https://gladiator.dosomething.org/competitions/265/messages/37) campaign are not sending. The messages are ending up in the `failed_jobs` table and never making it through.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UNPLANNED WORK:  🐛Leaderboard email send failure and display issue 🐛](https://trello.com/c/pf90ySIr/403-unplanned-work-leaderboard-email-send-failure-and-display-issue)
