### ISSUE TITLE
update db structure 

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#45]
New DB structure. 

**Overview:** A `Contest` is the umbrella container for everything. Each `Contest` has one `Waiting Room` that has sign up dates tied to it that can be set and edited by an admin as needed. `Waiting Rooms` get split into `Competitions`. Competitions hold groups of users competing in a contest and store the date the competition starts and the date they will end based on the run period of the `Contest`.

#### Contests
* `contest_id`
* `campaign_id` 
* `campaign_run_id`
* `waiting_room_id`
* How long the contest runs for (`duration`)

Also has (currently undetermined) metadata such as: 
* title 
* description
* prize (?)
* rules

#### Waiting Rooms
* `waiting_room_id`
* `contest_id`
* `signup_start_date` (admin can edit)
* `signup_end_date` (admin can edit)

#### Waiting Room Users
NOTE: I think this table exists already and should still work with this new structure:
`waiting_room_id`
`user_id`

#### Competitions
* `competition_id`
* `contest_id`
* `competition_start_date` (based on the day this competition was created)
* `competition_end_date` (calculated based on `run_period` and set on creation

#### Competition Users
* `competition_id`
* `user_id`

**Comment by angaither** [comment]
from @sbsmith86 
>  there will be a Brackets table that can have a model that defines all the methods we need to work with brackets. For example, per competition, we might want to show all the brackets, and then under each bracket, all of the users in that bracket.

**Comment by weerd** [comment]
#### Notes

Some thoughts to follow up on our #Slack conversation from last friday:

- Competition table holds all the metadata for a competition, stuff that maybe Phoenix would want to know of when setting up a competition signup popup, such as:
  - title
  - campaign_id
  - campaign_run_id
  - signup_copy
  - signup_button_text
  - confirmation_message
  - etc.
- Competitions could also hold the full timeline for a particular competition based on a series of dates:
  - signup_start (signup period to know if competition is active)
  - signup_end (signup period to know if competition is active)
  - competition_start
  - competition_end
- WaitingRooms are created for a specific Competition and should be considered a "contestant limbo" that temporary holds contestants until they are broken up into brackets at start of the next iteration of a particular competition.
- There can be some logic added that creates WaitingRooms for a Competition as the prior WaitingRoom closes and splits it's group of users. These WaitingRooms could be created up to the end of the Competition `signup_end` which would signal no more WaitingRooms cause we're on the last round of a Competition.

**Comment by deadlybutter** [comment]
> Competitions could also hold the full timeline for a particular competition based on a series of dates:

I was at first against this, BUT it would save admins from having to edit multiple things when setting up a competition. 

The competition_start / end should probably be bracket specific though, given different brackets could be running on different time tables.

**Comment by sbsmith86** [comment]
@weerd thanks for this! The last point is a little confusing to me and puts us back where we were last week when we were discussing if we need multiple waiting rooms or not. Why do we need multiple waiting rooms, instead of just changing the dates on one waiting room.

**Comment by sbsmith86** [comment]
@deadlybutter i think it should be a time period instead of specific dates, if we know a competition runs for a month, then each bracket can start at different times and we know when they need to close automatically.

**Comment by deadlybutter** [comment]
@sbsmith86 thats a great idea! agreed, lets change competition_start/end to competition_period, length, etc 

also I think we can automate the waiting room update as @weerd said, but we don't need to make a new waiting room as @sbsmith86 pointed out

**Comment by deadlybutter** [comment]
to expand on the waiting room automation,

I guess by default when you split the waiting room, it will adjust the current waiting room start to be *today* and then the end to be *7 days from now*. This could be changed by a form, but this will probably be whats normally used if i had to guess.

**Comment by weerd** [comment]
@joe, yeah i could see some dates added to the brackets, but I was thinking more about it like @sbsmith86 is suggesting and using logic based on known periods to dictate that. Plus, it'll confuse things if a bracket has `competition_start/end` dates but how does that relate to the parent competition's dates etc. Might just be a need to be mindful of what it's called... use `bracket_start/end`? I dunno.

@sbsmith86 yeah, I wasn't sure. Seemed like by the end of the convo last week we had suggested multiple WaitingRooms but not sure if everyone was sold on that. If it's 1 WaitingRoom does it even need dates? It could just be a collection bucket that collects users for a week, then they get split, bucket empties and is ready for next group... not sure if dates would play any useful role for the WaitingRoom bucket if it just gets reused. The dates would be the ones on the competition and if the date for signups passes, we can just close up the WaitingRoom bucket.

**Comment by sbsmith86** [comment]
@weerd hmmm that's an interesting point re: dates on waiting rooms. Yea I think there was some confusion about waiting rooms. Do they designate a new iteration of a competition? (as it seems @angaither was mentioning) or do they just serve the purpose of holding people until we split? I was confused about that.

**Comment by deadlybutter** [comment]
@weerd that logic requires a start date stored on the bracket still. (`bracket->start_date +1 month`)

also i still think waiting rooms show have a date, just so its clear to admins this waiting room will be split into competitions on <insert day>

**Comment by weerd** [comment]
@deadlybutter  gotcha re: bracket_start_date

@deadlybutter couldn't the waiting rooms have a period as well then? `7 days`

**Comment by weerd** [comment]
@sbsmith86 I kind of prefer this:

> How long the competition runs for (run_period)

To just be a `competition_start` `competition_end` dates which define the period.

And 

> competition_start_date (based on the day this bracket was created)
> competition_end_date (calculated based on run_period and set on creation

To be `bracket_start_date` and `bracket_end_date`. Feel this would be clearer.

**Comment by sbsmith86** [comment]
@weerd ah yes my bad about `bracket_start_date` and `bracket_end_date`. 

I'm not sure why we would want put specific dates on the competition, though. because not all brackets would start at the same time. So like the idea was to be able to say "Competition A runs for a month" and then everything gets calculated based on that.

**Comment by weerd** [comment]
Yeah, nevermind the first part of that comment... but does bring something to mind...

Maybe having both on Competition? So like when you create a competition admin would indicate, Competition period starts on March 10th and ends on April 15th. Then a separate field to indicate how long a `bracket_period_duration` lasts and that's an integer?

**Comment by deadlybutter** [comment]
I dont understand why we need to define the competition period. What problem is that solving?
