### ISSUE TITLE
Implement API Transformers & API Key

### ISSUE THREAD

**Issue by weerd** [DoSomething/gladiator#48]
Transformers, robots in disguise!
![image](https://cloud.githubusercontent.com/assets/105849/13535166/d1d09020-e206-11e5-9121-1cc1f7518d03.png)

Implement the use of API response Transformers using Fractal and add an API key so POST can't be sent to Gladiator anonymously!

Relates to recent work completed in #44

**Comment by weerd** [comment]
@jonuy I'm pinging you just so you can acknowledge the awesome Transformers pic I found for this issue :stuck_out_tongue_winking_eye:

**Comment by jonuy** [comment]
:+1: to the issue and the pic
