### ISSUE TITLE
Update Waiting Room Split functionality

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/gladiator#62]
Update the waiting room split functionality to work with the new DB structure, not sure how much of this needs to change, but this is a general outline of what should happen. 

* There is one waiting room per contest.
* When the sign up period is over there is an option to split the room. 
* The room gets split in to competitions.
* After split, the users get removed from that room and it can be reused if needed.

**Comment by deadlybutter** [comment]
I think this needs to be done https://github.com/DoSomething/gladiator/issues/59 before I can do this, is someone already working on #59 ?
