### ISSUE TITLE
update the contest create form

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#77]
it would be a lot easier to create a waiting room at the same time as a contest, so let's add the waiting room start and end dates to the contest form

**Comment by deadlybutter** [comment]
given that we removed the waiting room create functionality, I dont think we even have a way to make waiting rooms for competitions right now

oops

**Comment by sbsmith86** [comment]
We do create the waiting room at the same time as the contest. It gets created automatically when a contest gets created in the `ContestServiceProvider` but we do use default dates. We can probably just update that so that it uses dates from the contest create form.

**Comment by angaither** [comment]
right, I was thinking it would be easier to pull in the waiting room form into the contest form so it's not created behind the scenes automatically, but you can explicitly set the dates

**Comment by sbsmith86** [comment]
I'm wondering if we could just collect sign up period dates on the contest create form and send them to the function that is already handling waiting room creation.

**Comment by deadlybutter** [comment]
I think the solution @angaither proposed is easier cause I can just have a WaitingRoomRequest param and plug that into a new waiting room. also don't have to make new form stuff

**Comment by sbsmith86** [comment]
All we would have to do is use the `Request` facade in the service provider, and grab the sign up date period values from it when we create the waiting room. 

I guess i'm just confused as to why that option is not easy? Also it feels weird to me to have waiting room creation coupled to the contest controller like that when it is a completely different model. But I could be totally wrong! If I'm making this too complicated, we can scratch this, I'm just trying to understand.

**Comment by deadlybutter** [comment]
so something like this @sbsmith86 ?

```
                <form method="POST" action="{{ route('contests.store') }}">
                    <div class="form-item -padded">
                        {!! Form::label('signup_start_date', 'Signup Start Date: ', ['class' => 'field-label']) !!}
                        {!! Form::date('signup_start_date', NULL, ['class' => 'text-field']) !!}
                    </div>

                    <div class="form-item -padded">
                        {!! Form::label('signup_end_date', 'Signup End Date: ', ['class' => 'field-label']) !!}
                        {!! Form::date('signup_end_date', NULL, ['class' => 'text-field']) !!}
                    </div>
                    @include('contests.partials._form_contest')
                </form>
```

![screen shot 2016-03-14 at 10 21 22 am](https://cloud.githubusercontent.com/assets/897368/13747432/a4bcb238-e9ce-11e5-86b0-8fbfd3a7565d.png)

**Comment by sbsmith86** [comment]
Yea that is what the form would look like. Those fields might be able to live in the contest form partial, since we might want to allow admins to edit the dates in the contest form as well. 

and then in the service provider you would just have:

```
use Request;

// Create a new waiting room when a Contest is saved.
Contest::created(function ($contest) {
            $request = Request::all();

            $waitingRoom = new WaitingRoom;

            $waitingRoom->contest_id = $contest->getKey();

            // Default sign up period of one week.
            $waitingRoom->signup_start_date = $request->signup_start_date;
            $waitingRoom->signup_end_date = $request->signup_end_date;

            $waitingRoom->save();
 });
```

**Comment by deadlybutter** [comment]
is there ever a case where we need the waiting room partial then?

might be worth just hiding waiting rooms entirely from the user, and change the waiting room partial to just be the two date inputs (without the surrounding form, so it can be placed inside the contest partial?)

**Comment by sbsmith86** [comment]
Yea, I'm not sure. #77 seems to imply we are getting rid of the `edit` waiting rooms route, which would mean we don't really need a way to edit waiting rooms specifically at all, everything would just be handled at the contest level. 

If that is the case, we don't really need any of the waiting rooms routes or partials, except for maybe the ability to view a specific waiting room.
