### ISSUE TITLE
Contest index

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#78]
refs #77 

- add waiting room end date to the table index

- create two tables of contest index
 - open contests show on the top 
 - closed contests show under in a different table

**Comment by sbsmith86** [comment]
@angaither @mikefantini So one thing i'm wondering about this. 

> open contests show on the top
> closed contests show under in a different table

Do we want the concept of a contest being "open/closed" tied to the sign up period or to the face that the entire contest and competitions with that contest are over. 

Would it be weird to have a contest show up in the "closed" table when there are still active competitions within in it? 

/cc @deadlybutter @weerd

**Comment by deadlybutter** [comment]
we have a function on the waiting room called "isOpen" which calculates a boolean value if its open or not based on the dates. didn't think about considering whether we still have active competitions or not... hm.

**Comment by sbsmith86** [comment]
I'm sorta leaning to just adding a column to the index table that says if the waiting room is open or closed or not. We can still do this idea of two tables showing open and closed contests, but maybe that really speaks to the fact that closed contests are completely over, open contests still have things going on in them.

**Comment by deadlybutter** [comment]
+1 to just showing the column for waiting room open / closed

I had a idea in our sync im still thinking which might solve the second problem you described...

Can we make the homepage a calendar with all the competitions / waiting rooms?
