### ISSUE TITLE
remove waiting room routes and code

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#79]
- Hide contest id on edit of waiting room, this isn't super useful, especially if it's inherited on the contest form
- remove routes to create/edit waiting rooms explicity
- remove the waiting room link from the nav

**Comment by sbsmith86** [comment]
We are currently explicitly excluding the create and destroy routes on waiting rooms. Why do we need to remove the edit one?

**Comment by angaither** [comment]
@sbsmith86 my bad, I just most mean remove this from the menu so you don't look at a waiting room, you're just looking at a contest
