### ISSUE TITLE
need view to see users in waiting room on the contest view

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/gladiator#82]
It'd be helpful to know how many users are in a waiting room (and ideally who they are) before deciding to split or not.

Ideally this could be a new column on https://qa-gladiator.dosomething.org/waitingrooms where the number of users displays in the table and links to a view of who those users are.

Number of people in the waiting room should be the priority. This way Hillary and Chris can know how much traction the competition has received and if they should split it sooner rather than later given demand.

**Comment by sbsmith86** [comment]
@angaither @mikefantini can we connect on all of these waiting rooms updates ( #77, #79, #80) I feel like these issues are starting to overlap, overwrite each other.
