### ISSUE TITLE
Make it harder to delete

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#96]
on contests
and compeitions 

> some of this functionality is in aurora

**Comment by angaither** [comment]
@weerd @sbsmith86 @mikefantini is the red button enough? should this be closed out?

**Comment by mikefantini** [comment]
I don't think it's :cat2: proof enough. I think we need a confirmation "Are you sure you want to delete this?".* **

*I :heart: :cat2: 
** No :cat2: were harmed in the making of this comment.

**Comment by sbsmith86** [comment]
agree on a prompt to double check. Do we even need a delete button on the competition?

**Comment by angaither** [comment]
we could remove it

**Comment by mikefantini** [comment]
Ok so we're removing from competition, do we want to remove from contest too? Or just make that one way harder?

**Comment by angaither** [comment]
we should probably just remove both, since what happens to all the people if they are in a comp that gets deleted?

**Comment by mikefantini** [comment]
Yeah I'm good to remove both.
