### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by angaither** [DoSomething/gladiator#97]
Columns for leaderboard:

Rank | Name | Number of x's y'd | Email | Flagged Status
| --- | --- | --- | --- | --- |
1 | Jerome | 50 | jeromoe@example.com | approved
2 | Hils | 35 | hils@clinton.com | approved
3 | Bernie | 20 | bernie@sanders.com | approved

Sort by number of x's y'd.

If there is a pending file highlight the row in yellow, only show approved if there are NO PENDING files

Drop phone number

**Comment by mikefantini** [comment]
Columns for leaderboard:

Rank | Name | Number of x's y'd | Email | Flagged Status

Sort by number of x's y'd.

If there is a pending file highlight the row in yellow?

Drop phone number

**Comment by deadlybutter** [comment]
@angaither fixed the table
